import os
os.system("pip install Pillow")
os.system("pip install cryptg")
os.system("pip install nospamplus")
os.system("pip install pymediainfo")
os.system("pip install python-magic")
os.system("pip install pyseoanalyzer")
os.system("pip install glitch_this")
os.system("pip install PyGithub")
os.system("pip install pytesseract")
os.system("pip install youtube-dl")
os.system("pip install opencv-contrib-python")
os.system("pip install telethon>=1.17")
# In anonther Day
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")
os.system("pip install cryptg")

